=== dprint/dprint/website/assets/schemas/v0.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://dprint.dev/schemas/v1.json",
  "title": "Dprint Configuration File",
  "description": "Schema for a dprint configuration file.",
  "type": "object",
  "properties": {
    "$schema": {
      "description": "The JSON schema reference.",
      "type": "string"
    },
    "projectType": {
      "description": "The type of project Dprint is formatting.",
      "type": "string",
      "oneOf": [
        {
          "const": "openSource",
          "description": "Dprint is formatting an open source project."
        },
        {
          "const": "commercialSponsored",
          "description": "Dprint is formatting a commercial project and your company sponsored dprint. Thank you for being part of moving this project forward!"
        },
        {
          "const": "commercialDidNotSponsor",
          "description": "Dprint is formatting a commercial project and you are just trying it out or don't want to sponsor. If you are in the financial position to do so, please take the time to sponsor."
        }
      ]
    },
    "extends": {
      "description": "Configurations to extend.",
      "anyOf": [{
        "description": "A file path or url to a configuration file to extend.",
        "type": "string"
      }, {
        "description": "A collection of file paths and/or urls to configuration files to extend.",
        "type": "array",
        "items": {
          "type": "string"
        }
      }]
    },
    "lineWidth": {
      "description": "The width of a line the printer will try to stay under. Note that the printer may exceed this width in certain cases.",
      "type": "number",
      "default": 120
    },
    "indentWidth": {
      "description": "The number of characters for an indent.",
      "type": "number",
      "default": 4
    },
    "useTabs": {
      "description": "Whether to use tabs (true) or spaces (false) for indentation.",
      "type": "boolean",
      "default": false
    },
    "newlineKind": {
      "description": "The kind of newline to use.",
      "type": "string",
      "oneOf": [
        {
          "const": "auto",
          "description": "For each file, uses the newline kind found at the end of the last line."
        },
        {
          "const": "crlf",
          "description": "Uses carriage return, line feed."
        },
        {
          "const": "lf",
          "description": "Uses line feed."
        },
        {
          "const": "system",
          "description": "Uses the system standard (ex. crlf on Windows)."
        }
      ]
    },
    "includes": {
      "description": "Array of patterns (globs) to use to find files to format.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "excludes": {
      "description": "Array of patterns (globs) to exclude files or directories to format.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "plugins": {
      "description": "Array of plugin URLs to format files.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "typescript": {
      "$ref": "https://plugins.dprint.dev/schemas/typescript-v0.json"
    },
    "javascript": {
      "$ref": "https://plugins.dprint.dev/schemas/typescript-v0.json"
    },
    "json": {
      "$ref": "https://plugins.dprint.dev/schemas/json-v0.json"
    },
    "jsonc": {
      "$ref": "https://plugins.dprint.dev/schemas/json-v0.json"
    }
  },
  "additionalProperties": {
    "description": "Plugin configuration.",
    "type": "object"
  }
}

=== dprint/dprint/dprint.config.json
{
  "$schema": "https://dprint.dev/schemas/v0.json",
  "projectType": "openSource",
  "lineWidth": 160,
  "typescript": {
    "useBraces": "preferNone",
    "singleBodyPosition": "nextLine",
    "preferHanging": true,
    "preferSingleLine": false,
    "nextControlFlowPosition": "nextLine",
    "semiColons": "always",
    "arrowFunction.useParentheses": "preferNone",
    "tryStatement.nextControlFlowPosition": "sameLine"
  },
  "json": {
    "indentWidth": 2
  },
  "includes": [
    "**/*.{ts,tsx,js,jsx,json}"
  ],
  "excludes": [
    "packages/playground/public/vs",
    "packages/playground/build",
    "build-website",
    "**/dist",
    "**/target",
    "**/wasm"
  ],
  "plugins": [
    "https://plugins.dprint.dev/typescript-0.19.0.wasm",
    "https://plugins.dprint.dev/json-0.4.0.wasm"
  ]
}
